# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20171012_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='req',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
