# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0009_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs', models.BooleanField(default=False)),
                ('tick', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('dpts', models.CharField(max_length=100)),
                ('coment', models.TextField()),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Logeado')),
            ],
        ),
    ]
