# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin', '0003_auto_20171012_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
