# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='state',
        ),
        migrations.AddField(
            model_name='document',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='print',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='send',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
