# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20170830_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='change',
            field=models.BooleanField(default=False),
        ),
    ]
