# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='change',
            field=models.BooleanField(),
        ),
    ]
