# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20170906_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='previous',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
