# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_previous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='footer',
            field=models.TextField(blank=True, default='NA'),
        ),
    ]
