# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logeado',
            name='departament',
            field=models.CharField(default='default', max_length=300),
        ),
    ]
