# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20170907_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logeado',
            name='departament',
            field=models.CharField(default='1,', max_length=30),
        ),
    ]
