# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20170907_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='logeado',
            name='set_departamen',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
