# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_logeado_set_departamen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logeado',
            old_name='set_departamen',
            new_name='set_departament',
        ),
    ]
