# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='logeado',
            name='tick',
            field=models.BooleanField(default=False),
        ),
    ]
