# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_logeado_tick'),
    ]

    operations = [
        migrations.AddField(
            model_name='logeado',
            name='cellphone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logeado',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
