# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20171018_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logeado',
            name='avatar',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='logeado',
            name='departament',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='logeado',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='logeado',
            name='set_departament',
            field=models.IntegerField(default=1),
        ),
    ]
