# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20171122_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logeado',
            name='set_departament',
            field=models.IntegerField(),
        ),
    ]
