# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='usuario',
        ),
    ]
