# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Ticket', '0003_auto_20171018_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='asignado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
