# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Ticket', '0004_auto_20171018_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestas',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Ticket.Ticket'),
        ),
        migrations.AlterField(
            model_name='respuestas',
            name='usuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
