# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Ticket', '0005_auto_20171019_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestas',
            name='asunto',
            field=models.CharField(max_length=100),
        ),
    ]
