# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Ticket', '0007_auto_20171019_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestas',
            name='asunto',
        ),
    ]
