# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Ticket', '0008_remove_respuestas_asunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='App_Ticket.Estado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fijo_contacto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
