# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Ticket', '0010_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='nombre',
        ),
        migrations.AddField(
            model_name='tecnico',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
