# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
